### ISSUE TITLE
GNURadioCompanion module 'gi' has no attribute 'require_version'

### ISSUE THREAD

**Issue by loic-fejoz** [f4iey/f6kgl-os#5]
```
liveuser@f6kgl ~ % gnuradio-companion 
While trying to display an error message, another error occurred
module 'gi' has no attribute 'require_version'
The original error message follows.
AttributeError

Failed to initialize GTK. If you are running over ssh, did you enable X forwarding and start ssh with -X?

(module 'gi' has no attribute 'require_version')

```

**Comment by f4iey** [comment]
It is because `gnuradio-companion` is missing dependencies (like `python-gobject` and `python-cairo`). By default, `gnuradio-companion` is *not* installed on F6KGL OS; the gnuradio dependencies are there for `gqrx`. But KDE Plasma is messing around with the launcher.
![image](https://user-images.githubusercontent.com/93203507/151169454-b7d9dc5b-c913-4162-9d85-0734a8b190a0.png)
